default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    # High priority queue for critical jobs (security alerts, notifications)
    - queues: "critical,high_priority"
      threads: 2
      processes: <%= ENV.fetch("CRITICAL_JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    # Default queue for regular background jobs
    - queues: "default,low_priority"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 1
    # Dedicated worker for caching and analytics jobs
    - queues: "caching,analytics"
      threads: 2
      processes: 1
      polling_interval: 2

development:
  <<: *default
  workers:
    # Simplified setup for development
    - queues: "*"
      threads: 2
      processes: 1
      polling_interval: 1

test:
  <<: *default
  workers:
    # Minimal setup for testing
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 0.1

production:
  <<: *default
  workers:
    # High priority queue for critical jobs
    - queues: "critical,high_priority"
      threads: 4
      processes: <%= ENV.fetch("CRITICAL_JOB_CONCURRENCY", 2) %>
      polling_interval: 0.1
    # Default queue for regular background jobs
    - queues: "default,low_priority"
      threads: 6
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 3) %>
      polling_interval: 1
    # Dedicated workers for heavy operations
    - queues: "caching,analytics,reports"
      threads: 4
      processes: 2
      polling_interval: 2
